// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infastructure/database/database.go

// Package mock_database is a generated GoMock package.
package mock_database

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	datasource "github.com/nutsp/golang-clean-architecture/pkg/datasource"
)

// MockIDatabase is a mock of IDatabase interface.
type MockIDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockIDatabaseMockRecorder
}

// MockIDatabaseMockRecorder is the mock recorder for MockIDatabase.
type MockIDatabaseMockRecorder struct {
	mock *MockIDatabase
}

// NewMockIDatabase creates a new mock instance.
func NewMockIDatabase(ctrl *gomock.Controller) *MockIDatabase {
	mock := &MockIDatabase{ctrl: ctrl}
	mock.recorder = &MockIDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDatabase) EXPECT() *MockIDatabaseMockRecorder {
	return m.recorder
}

// GptDB mocks base method.
func (m *MockIDatabase) GptDB() datasource.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GptDB")
	ret0, _ := ret[0].(datasource.DB)
	return ret0
}

// GptDB indicates an expected call of GptDB.
func (mr *MockIDatabaseMockRecorder) GptDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GptDB", reflect.TypeOf((*MockIDatabase)(nil).GptDB))
}

// OllamaDB mocks base method.
func (m *MockIDatabase) OllamaDB() datasource.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OllamaDB")
	ret0, _ := ret[0].(datasource.DB)
	return ret0
}

// OllamaDB indicates an expected call of OllamaDB.
func (mr *MockIDatabaseMockRecorder) OllamaDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OllamaDB", reflect.TypeOf((*MockIDatabase)(nil).OllamaDB))
}
