App:
  Name: "golang-clean-architecture"
  Version: "v0.0.1"
  Scheme: "http"
  Host: "localhost:3002"
  Environment: local #local,development,staging,production

Server:
  Port: "9090"
  Debug: true
  TimeZone: "Asia/Bangkok"


Database: 
  Host: 127.0.0.1
  Port: 3306
  Name: test
  User: root
  Password: 1234

Redis:
  Addr: 127.0.0.1:6379
  Password:
  DB: 0

Logger:
  Mode: production
  Encoding: json

Authentication:
  Key: DoWithLogic!@#

Observability:
  Enable: false
  Mode: "otlp/http"